In [9]:
import pandas as pd

file_path = '../datasets/movies_vector.csv'
df = pd.read_csv(file_path)

df.head()

,id,title,summary,year,genre,certificate,runtime,rating,votes,sentiment,img,metadata,metadata_vector
0,15239678,Dune: Part Two,Paul Atreides unites with Chani and the Fremen...,2024,Adventure,PG-13,2h 46m,8.7,360000,-0.7650,https://m.media-amazon.com/images/M/MV5BN2QyZG...,Dune: Part Two | Paul Atreides unites with Cha...,"[-0.011729336343705654, 0.04041394963860512, 0..."
1,14539740,Godzilla x Kong: The New Empire,"Two ancient titans, Godzilla and Kong, clash i...",2024,Adventure,PG-13,1h 55m,6.5,37000,-0.3818,https://m.media-amazon.com/images/M/MV5BY2QwOG...,Godzilla x Kong: The New Empire | Two ancient ...,"[0.007644626311957836, 0.03877980634570122, 0...."
2,23137904,Rebel Moon - Part Two: The Scargiver,Kora and surviving warriors prepare to defend ...,2024,Adventure,PG-13,2h 2m,5.2,17000,0.2023,https://m.media-amazon.com/images/M/MV5BYmQ2OD...,Rebel Moon - Part Two: The Scargiver | Kora an...,"[0.043467093259096146, 0.0680377185344696, 0.0..."
3,21692408,Kung Fu Panda 4,After Po is tapped to become the Spiritual Lea...,2024,Adventure,PG,1h 34m,6.4,30000,-0.8957,https://m.media-amazon.com/images/M/MV5BZDY0Yz...,Kung Fu Panda 4 | After Po is tapped to become...,"[-0.018895048648118973, 0.019839802756905556, ..."
4,1160419,Dune,A noble family becomes embroiled in a war for ...,2021,Adventure,PG-13,2h 35m,8.0,851000,0.4890,https://m.media-amazon.com/images/M/MV5BMDQ0Nj...,Dune | A noble family becomes embroiled in a w...,"[-0.04253479093313217, 0.03401784226298332, 0...."

In [10]:
def runtime_to_minutes(time_str):
    if 'h' in time_str:
        # Splitting hours and minutes
        parts = time_str.split('h ')
        # Extracting numerical part for hours
        hours = int(parts[0].replace('h', ''))
        if len(parts) > 1 and 'm' in parts[1]:
            minutes = int(parts[1][:-1])
        else:
            minutes = 0
    else:
        # If there are no hours, set it to 0
        hours = 0
        if 'm' in time_str:
            minutes = int(time_str[:-1])
        else:
            minutes = 0

    # Calculating total minutes
    total_minutes = hours * 60 + minutes
    return total_minutes

# Apply the function to each value in the 'runtime' column and create a new column 'runtime_mins'
df['runtime_mins'] = df['runtime'].apply(runtime_to_minutes)

# Print the DataFrame to verify the new column
print(df.head())

         id                                 title  \
0  15239678                        Dune: Part Two
1  14539740       Godzilla x Kong: The New Empire
2  23137904  Rebel Moon - Part Two: The Scargiver
3  21692408                       Kung Fu Panda 4
4   1160419                                  Dune

                                             summary  year      genre  \
0  Paul Atreides unites with Chani and the Fremen...  2024  Adventure
1  Two ancient titans, Godzilla and Kong, clash i...  2024  Adventure
2  Kora and surviving warriors prepare to defend ...  2024  Adventure
3  After Po is tapped to become the Spiritual Lea...  2024  Adventure
4  A noble family becomes embroiled in a war for ...  2021  Adventure

  certificate runtime  rating   votes  sentiment  \
0       PG-13  2h 46m     8.7  360000    -0.7650
1       PG-13  1h 55m     6.5   37000    -0.3818
2       PG-13   2h 2m     5.2   17000     0.2023
3          PG  1h 34m     6.4   30000    -0.8957
4       PG-13  2h 35m     8.0  851000     0.4890

                                                 img  \
0  https://m.media-amazon.com/images/M/MV5BN2QyZG...
1  https://m.media-amazon.com/images/M/MV5BY2QwOG...
2  https://m.media-amazon.com/images/M/MV5BYmQ2OD...
3  https://m.media-amazon.com/images/M/MV5BZDY0Yz...
4  https://m.media-amazon.com/images/M/MV5BMDQ0Nj...

                                            metadata  \
0  Dune: Part Two | Paul Atreides unites with Cha...
1  Godzilla x Kong: The New Empire | Two ancient ...
2  Rebel Moon - Part Two: The Scargiver | Kora an...
3  Kung Fu Panda 4 | After Po is tapped to become...
4  Dune | A noble family becomes embroiled in a w...

                                     metadata_vector  runtime_mins
0  [-0.011729336343705654, 0.04041394963860512, 0...           166
1  [0.007644626311957836, 0.03877980634570122, 0....           115
2  [0.043467093259096146, 0.0680377185344696, 0.0...           122
3  [-0.018895048648118973, 0.019839802756905556, ...            94
4  [-0.04253479093313217, 0.03401784226298332, 0....           155

In [11]:
df.head()

,id,title,summary,year,genre,certificate,runtime,rating,votes,sentiment,img,metadata,metadata_vector,runtime_mins
0,15239678,Dune: Part Two,Paul Atreides unites with Chani and the Fremen...,2024,Adventure,PG-13,2h 46m,8.7,360000,-0.7650,https://m.media-amazon.com/images/M/MV5BN2QyZG...,Dune: Part Two | Paul Atreides unites with Cha...,"[-0.011729336343705654, 0.04041394963860512, 0...",166
1,14539740,Godzilla x Kong: The New Empire,"Two ancient titans, Godzilla and Kong, clash i...",2024,Adventure,PG-13,1h 55m,6.5,37000,-0.3818,https://m.media-amazon.com/images/M/MV5BY2QwOG...,Godzilla x Kong: The New Empire | Two ancient ...,"[0.007644626311957836, 0.03877980634570122, 0....",115
2,23137904,Rebel Moon - Part Two: The Scargiver,Kora and surviving warriors prepare to defend ...,2024,Adventure,PG-13,2h 2m,5.2,17000,0.2023,https://m.media-amazon.com/images/M/MV5BYmQ2OD...,Rebel Moon - Part Two: The Scargiver | Kora an...,"[0.043467093259096146, 0.0680377185344696, 0.0...",122
3,21692408,Kung Fu Panda 4,After Po is tapped to become the Spiritual Lea...,2024,Adventure,PG,1h 34m,6.4,30000,-0.8957,https://m.media-amazon.com/images/M/MV5BZDY0Yz...,Kung Fu Panda 4 | After Po is tapped to become...,"[-0.018895048648118973, 0.019839802756905556, ...",94
4,1160419,Dune,A noble family becomes embroiled in a war for ...,2021,Adventure,PG-13,2h 35m,8.0,851000,0.4890,https://m.media-amazon.com/images/M/MV5BMDQ0Nj...,Dune | A noble family becomes embroiled in a w...,"[-0.04253479093313217, 0.03401784226298332, 0....",155

In [13]:
unique_runtimes = df['runtime_mins'].unique()
for runtime in unique_runtimes:
    print(runtime)

166
115
122
94
155
133
95
110
169
116
137
114
144
124
127
157
158
83
152
148
163
120
107
178
90
142
153
140
84
121
92
139
130
103
181
192
91
143
150
98
201
132
104
119
134
123
126
147
141
88
162
118
89
105
172
156
125
129
149
112
154
136
146
187
102
99
135
93
81
128
179
100
131
97
145
101
111
113
108
151
117
138
161
242
96
220
197
109
86
218
212
106
87
165
164
85
78
185
160
79
210
191
69
76
75
77
80
177
82
193
74
219
173
63
168
64
182
175
72
167
170
207
68
71
73
70
188
46
51
48
206
194
238
180
183
174
171
159
189
186
195
200
237
374
45
208
65
216
176
213
59
56
224
184
467
209
202
260
204
247
321
57
67
54
55
566
240
62
66
271
229
317
196
439

In [14]:
# Move 'runtime_mins' column after 'runtime'
runtime_mins_col = df.pop('runtime_mins')
df.insert(df.columns.get_loc('runtime') + 1, 'runtime_mins', runtime_mins_col)

df.head()

,id,title,summary,year,genre,certificate,runtime,runtime_mins,rating,votes,sentiment,img,metadata,metadata_vector
0,15239678,Dune: Part Two,Paul Atreides unites with Chani and the Fremen...,2024,Adventure,PG-13,2h 46m,166,8.7,360000,-0.7650,https://m.media-amazon.com/images/M/MV5BN2QyZG...,Dune: Part Two | Paul Atreides unites with Cha...,"[-0.011729336343705654, 0.04041394963860512, 0..."
1,14539740,Godzilla x Kong: The New Empire,"Two ancient titans, Godzilla and Kong, clash i...",2024,Adventure,PG-13,1h 55m,115,6.5,37000,-0.3818,https://m.media-amazon.com/images/M/MV5BY2QwOG...,Godzilla x Kong: The New Empire | Two ancient ...,"[0.007644626311957836, 0.03877980634570122, 0...."
2,23137904,Rebel Moon - Part Two: The Scargiver,Kora and surviving warriors prepare to defend ...,2024,Adventure,PG-13,2h 2m,122,5.2,17000,0.2023,https://m.media-amazon.com/images/M/MV5BYmQ2OD...,Rebel Moon - Part Two: The Scargiver | Kora an...,"[0.043467093259096146, 0.0680377185344696, 0.0..."
3,21692408,Kung Fu Panda 4,After Po is tapped to become the Spiritual Lea...,2024,Adventure,PG,1h 34m,94,6.4,30000,-0.8957,https://m.media-amazon.com/images/M/MV5BZDY0Yz...,Kung Fu Panda 4 | After Po is tapped to become...,"[-0.018895048648118973, 0.019839802756905556, ..."
4,1160419,Dune,A noble family becomes embroiled in a war for ...,2021,Adventure,PG-13,2h 35m,155,8.0,851000,0.4890,https://m.media-amazon.com/images/M/MV5BMDQ0Nj...,Dune | A noble family becomes embroiled in a w...,"[-0.04253479093313217, 0.03401784226298332, 0...."

In [16]:
from sklearn.preprocessing import MinMaxScaler

# Define the scaler
scaler = MinMaxScaler(feature_range=(1, 5))

# Fit and transform the data
scaled_sentiment = scaler.fit_transform(df[['sentiment']])

# Round the scaled values to the nearest integer
rounded_sentiment = [round(value) for value in scaled_sentiment.flatten()]

# Store the rounded values in a new column
df['sentiment_normalized'] = rounded_sentiment
df.head()

,id,title,summary,year,genre,certificate,runtime,runtime_mins,rating,votes,sentiment,img,metadata,metadata_vector,sentiment_normalized
0,15239678,Dune: Part Two,Paul Atreides unites with Chani and the Fremen...,2024,Adventure,PG-13,2h 46m,166,8.7,360000,-0.7650,https://m.media-amazon.com/images/M/MV5BN2QyZG...,Dune: Part Two | Paul Atreides unites with Cha...,"[-0.011729336343705654, 0.04041394963860512, 0...",1
1,14539740,Godzilla x Kong: The New Empire,"Two ancient titans, Godzilla and Kong, clash i...",2024,Adventure,PG-13,1h 55m,115,6.5,37000,-0.3818,https://m.media-amazon.com/images/M/MV5BY2QwOG...,Godzilla x Kong: The New Empire | Two ancient ...,"[0.007644626311957836, 0.03877980634570122, 0....",2
2,23137904,Rebel Moon - Part Two: The Scargiver,Kora and surviving warriors prepare to defend ...,2024,Adventure,PG-13,2h 2m,122,5.2,17000,0.2023,https://m.media-amazon.com/images/M/MV5BYmQ2OD...,Rebel Moon - Part Two: The Scargiver | Kora an...,"[0.043467093259096146, 0.0680377185344696, 0.0...",3
3,21692408,Kung Fu Panda 4,After Po is tapped to become the Spiritual Lea...,2024,Adventure,PG,1h 34m,94,6.4,30000,-0.8957,https://m.media-amazon.com/images/M/MV5BZDY0Yz...,Kung Fu Panda 4 | After Po is tapped to become...,"[-0.018895048648118973, 0.019839802756905556, ...",1
4,1160419,Dune,A noble family becomes embroiled in a war for ...,2021,Adventure,PG-13,2h 35m,155,8.0,851000,0.4890,https://m.media-amazon.com/images/M/MV5BMDQ0Nj...,Dune | A noble family becomes embroiled in a w...,"[-0.04253479093313217, 0.03401784226298332, 0....",4

In [17]:
normalized_sentiment = df.pop('sentiment_normalized')

# Insert the 'normalized_sentiment' column after the 'sentiment' column
df.insert(df.columns.get_loc('sentiment') + 1, 'sentiment_normalized', normalized_sentiment)

# Print the DataFrame with reordered columns
df.head()

,id,title,summary,year,genre,certificate,runtime,runtime_mins,rating,votes,sentiment,sentiment_normalized,img,metadata,metadata_vector
0,15239678,Dune: Part Two,Paul Atreides unites with Chani and the Fremen...,2024,Adventure,PG-13,2h 46m,166,8.7,360000,-0.7650,1,https://m.media-amazon.com/images/M/MV5BN2QyZG...,Dune: Part Two | Paul Atreides unites with Cha...,"[-0.011729336343705654, 0.04041394963860512, 0..."
1,14539740,Godzilla x Kong: The New Empire,"Two ancient titans, Godzilla and Kong, clash i...",2024,Adventure,PG-13,1h 55m,115,6.5,37000,-0.3818,2,https://m.media-amazon.com/images/M/MV5BY2QwOG...,Godzilla x Kong: The New Empire | Two ancient ...,"[0.007644626311957836, 0.03877980634570122, 0...."
2,23137904,Rebel Moon - Part Two: The Scargiver,Kora and surviving warriors prepare to defend ...,2024,Adventure,PG-13,2h 2m,122,5.2,17000,0.2023,3,https://m.media-amazon.com/images/M/MV5BYmQ2OD...,Rebel Moon - Part Two: The Scargiver | Kora an...,"[0.043467093259096146, 0.0680377185344696, 0.0..."
3,21692408,Kung Fu Panda 4,After Po is tapped to become the Spiritual Lea...,2024,Adventure,PG,1h 34m,94,6.4,30000,-0.8957,1,https://m.media-amazon.com/images/M/MV5BZDY0Yz...,Kung Fu Panda 4 | After Po is tapped to become...,"[-0.018895048648118973, 0.019839802756905556, ..."
4,1160419,Dune,A noble family becomes embroiled in a war for ...,2021,Adventure,PG-13,2h 35m,155,8.0,851000,0.4890,4,https://m.media-amazon.com/images/M/MV5BMDQ0Nj...,Dune | A noble family becomes embroiled in a w...,"[-0.04253479093313217, 0.03401784226298332, 0...."

In [18]:
df.rename(columns={'sentiment': 'sentiment_compound'}, inplace=True)
df.head()

,id,title,summary,year,genre,certificate,runtime,runtime_mins,rating,votes,sentiment_compound,sentiment_normalized,img,metadata,metadata_vector
0,15239678,Dune: Part Two,Paul Atreides unites with Chani and the Fremen...,2024,Adventure,PG-13,2h 46m,166,8.7,360000,-0.7650,1,https://m.media-amazon.com/images/M/MV5BN2QyZG...,Dune: Part Two | Paul Atreides unites with Cha...,"[-0.011729336343705654, 0.04041394963860512, 0..."
1,14539740,Godzilla x Kong: The New Empire,"Two ancient titans, Godzilla and Kong, clash i...",2024,Adventure,PG-13,1h 55m,115,6.5,37000,-0.3818,2,https://m.media-amazon.com/images/M/MV5BY2QwOG...,Godzilla x Kong: The New Empire | Two ancient ...,"[0.007644626311957836, 0.03877980634570122, 0...."
2,23137904,Rebel Moon - Part Two: The Scargiver,Kora and surviving warriors prepare to defend ...,2024,Adventure,PG-13,2h 2m,122,5.2,17000,0.2023,3,https://m.media-amazon.com/images/M/MV5BYmQ2OD...,Rebel Moon - Part Two: The Scargiver | Kora an...,"[0.043467093259096146, 0.0680377185344696, 0.0..."
3,21692408,Kung Fu Panda 4,After Po is tapped to become the Spiritual Lea...,2024,Adventure,PG,1h 34m,94,6.4,30000,-0.8957,1,https://m.media-amazon.com/images/M/MV5BZDY0Yz...,Kung Fu Panda 4 | After Po is tapped to become...,"[-0.018895048648118973, 0.019839802756905556, ..."
4,1160419,Dune,A noble family becomes embroiled in a war for ...,2021,Adventure,PG-13,2h 35m,155,8.0,851000,0.4890,4,https://m.media-amazon.com/images/M/MV5BMDQ0Nj...,Dune | A noble family becomes embroiled in a w...,"[-0.04253479093313217, 0.03401784226298332, 0...."

In [19]:
df.to_csv("movies_final.csv", index=False)

In [20]:
df.drop(columns=['metadata', 'metadata_vector'], inplace=True)
df.head()

,id,title,summary,year,genre,certificate,runtime,runtime_mins,rating,votes,sentiment_compound,sentiment_normalized,img
0,15239678,Dune: Part Two,Paul Atreides unites with Chani and the Fremen...,2024,Adventure,PG-13,2h 46m,166,8.7,360000,-0.7650,1,https://m.media-amazon.com/images/M/MV5BN2QyZG...
1,14539740,Godzilla x Kong: The New Empire,"Two ancient titans, Godzilla and Kong, clash i...",2024,Adventure,PG-13,1h 55m,115,6.5,37000,-0.3818,2,https://m.media-amazon.com/images/M/MV5BY2QwOG...
2,23137904,Rebel Moon - Part Two: The Scargiver,Kora and surviving warriors prepare to defend ...,2024,Adventure,PG-13,2h 2m,122,5.2,17000,0.2023,3,https://m.media-amazon.com/images/M/MV5BYmQ2OD...
3,21692408,Kung Fu Panda 4,After Po is tapped to become the Spiritual Lea...,2024,Adventure,PG,1h 34m,94,6.4,30000,-0.8957,1,https://m.media-amazon.com/images/M/MV5BZDY0Yz...
4,1160419,Dune,A noble family becomes embroiled in a war for ...,2021,Adventure,PG-13,2h 35m,155,8.0,851000,0.4890,4,https://m.media-amazon.com/images/M/MV5BMDQ0Nj...

In [21]:
df.to_csv("movies.csv", index=False)